version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management   # 관리 UI 포함된 이미지
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP 프로토콜 (Spring, Node, Python 등에서 연결할 때 사용)
      - "15672:15672" # Management UI (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest   # 기본 사용자명
      RABBITMQ_DEFAULT_PASS: guest   # 기본 비밀번호
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # 데이터 영구 저장

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  sj-member-service:
    image: sooong137/sj-member-service:1.1
    container_name: sj-member-service
#    ports:
#      - "8082:8080"
    network_mode: host   # EC2 내부 네트워크 사용
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_INSTANCE_IP_ADDRESS=${EUREKA_INSTANCE_IP_ADDRESS}
      - JAVA_OPTS=-Xmx512m -Xms256m
    restart: always
    depends_on:
      - rabbitmq
      - kafka

volumes:
  rabbitmq_data: